"""English copy for Line Up Surf House. FR lives in fr.py with the SAME keys (phase 3).

Every factual line traces to SOURCE_OF_TRUTH.md; PROBABLE facts are softened ("often",
"some evenings", "ask us"). Inline HTML is allowed in values; build.py escapes nothing here.
"""

LANG = "en"
LOCALE = "en_GB"

UI = {
    "skip": "Skip to content",
    "menu": "Menu",
    "close": "Close",
    "nav_label": "Main",
    "brand_sub": "Surf House · Anza",
    "cta_ask": "Ask for dates",
    "cta_booking": "Booking.com",
    "cta_booking_long": "See us on Booking.com",
    "cta_whatsapp": "WhatsApp",
    "cta_whatsapp_long": "WhatsApp us",
    "cta_call": "Call",
    "lang_switch": "Français",
    "lang_switch_short": "FR",
    "ext": "opens in a new tab",
    "wa_hello": "Hello Line Up! I'd like to ask about a stay.",
}

# Navigation: page keys resolve to the built page, or to a homepage anchor until that page exists.
NAV = [
    ("rooms", "Rooms"),
    ("surf", "Surf school"),
    ("house", "The house"),
    ("anza", "Anza"),
]

PAGES_META = {
    "home": {
        "title": "Line Up Surf House · Anza, Agadir — surf house beside the break",
        "description": "Eight private rooms a few steps from Anza beach, breakfast made by our family, and our own surf school and board shop on the ground floor. Ask for dates on WhatsApp.",
        "og_title": "Line Up Surf House — stay beside the break in Anza",
    },
    "404": {
        "title": "Page not found · Line Up Surf House",
        "description": "This page drifted off. Head back to Line Up Surf House in Anza, Agadir.",
    },
}

HOME = {
    "cover": {
        "kicker": "Surf house · Anza beach, Agadir",
        "h1": "Stay beside <span>the break.</span>",
        "lead": "Eight private rooms a few steps from Anza beach. Breakfast made at home by our family. Our own surf school and board shop on the ground floor.",
        "rating_score": "9.6",
        "rating_on": "on Booking.com ·",
        "rating_link": "Book there",
        "horizon": "the line-up",
        "img_alt": "Anza beach seen from upstairs at Line Up: the beach car park, the sand, white water and the Atlantic horizon under a clear blue sky",
        "caption": "Anza beach from upstairs at Line Up",
    },
    "ch1": {
        "id": "morning",
        "n": "01",
        "label": "First light",
        "title": "Check the water before breakfast.",
        "lead": "Four of our eight rooms look straight over the beach to the surf. Open the shutter, see what the sea is doing, then head upstairs to eat.",
        "img_alt": "A dark window frame in a sea-view room at Line Up, looking over the beach car park to the sand and the sea",
        "caption": "From a sea-view room",
        "bf_title": "Breakfast, made at home",
        "bf_text": "Breakfast comes with every room, and our family makes it every morning. It’s vegetarian and halal, and it changes from day to day.",
        "bf_maybe": "Today, maybe",
        "bf_items": ["fresh orange juice", "eggs", "Moroccan pancakes", "bread", "honey", "olives", "mint tea or coffee"],
        "bf_note": "Gluten-free? Leaving for an early flight? Tell us, and we’ll do what we can.",
        "quote": "The breakfast was simple and tasty, and came with a great view from the rooftop.",
        "quote_by": "Katharina, Canada",
        "quote_src": "Booking.com",
    },
    "ch2": {
        "id": "surf",
        "n": "02",
        "label": "First session",
        "title": "Downstairs: the surf school.",
        "lead": "The ground floor of the house is our surf school and shop. Boards on the racks, wetsuits on the rail, and the beach just across the car park.",
        "items": [
            ("Lessons", "First-timers and improvers, adults and kids. Private or in a small group — tell us your level and we’ll suggest what suits you."),
            ("Rental", "Soft-tops, hard boards and wetsuits, right at the door."),
            ("Prices", "Ask for today’s price on WhatsApp."),
        ],
        "who": "Zohair is often the one in the water with you.",
        "quote": "He was very professional, patient, he explained everything and he was with us all the time in the water.",
        "quote_by": "Youness, Morocco",
        "quote_src": "Booking.com",
        "set_label": "Line Up surf school and shop",
        "set": [
            ("shopfront", "The front of Line Up: white house with blue window frames, the shop doors open under the LINE UP mural, a blue surfboard on trestles", "Our shop door. The banner says: “We are not the only ones but we are the best.”"),
            ("boards", "Yellow soft-top surfboards leaning against the painted LINE UP mural outside the shop", "Soft-tops, ready by the mural"),
            ("wetsuits", "Inside the Line Up shop: wetsuits on a rail, yellow Line Up T-shirts and a rack of yellow boards", "Wetsuits, boards, Line Up tees"),
        ],
    },
    "ch3": {
        "id": "midday",
        "n": "03",
        "label": "Midday",
        "title": "Midday: eat, rest, wander.",
        "rooms_id": "rooms",
        "rooms_title": "Eight rooms. No dorms.",
        "rooms_lead": "Every room is private, new and very clean, with towels, a shower and free Wi-Fi. The doors carry names from the water — look for “Reef room” and “Open face”.",
        "rooms": [
            {"img": "room-seaview", "count": "×2", "kind": "Sea view", "name": "Double or twin",
             "facts": ["King bed or two singles", "Up to 2 guests", "Window over the beach", "Shared bathroom outside the room"],
             "alt": "Sea-view twin room at Line Up: two single beds with brown covers and a folded LINE UP towel"},
            {"img": "room-triple", "count": "×2", "kind": "Sea view", "name": "Triple",
             "facts": ["Three singles, or a single and a king", "Up to 3 guests", "Big window to the sea", "Shared bathroom outside the room"],
             "alt": "Sea-view triple room at Line Up: a bed beside a wide open window with the beach and sea outside"},
            {"img": "room-private", "count": "×2", "kind": "Private bathroom", "name": "Double or twin",
             "facts": ["King bed or two singles", "Up to 2 guests", "Your own shower room"],
             "alt": "Double room with private bathroom at Line Up: a wide bed with LINE UP towels in a clean white room"},
            {"img": "room-compact", "count": "×2", "kind": "Compact", "name": "Double or twin",
             "facts": ["King bed or two singles", "Up to 2 guests", "Ask us about the bathroom set-up"],
             "plaques": ["Open face", "Reef room"],
             "alt": "The pine door of the ‘Open face’ room at Line Up, its wooden name plaque above, and a double bed inside"},
        ],
        "rooms_note": "Check-in 14:00 to midnight · check-out by 12:00 · children over 5 welcome · no cribs or extra beds · no pets, no parties",
        "lunch_title": "Lunch at home, if you ask",
        "lunch_text": "Order ahead and the family will cook a Moroccan meal for lunch or dinner — a chicken or kefta tajine, maybe lubya. It’s home cooking, not a restaurant, and it’s paid separately.",
        "anza_id": "anza",
        "anza_title": "Anza, around the house",
        "anza_text": "Anza is a quiet, local surf town on the edge of Agadir — less polished than Taghazout, and we like it that way. There are dinosaur footprints in the rocks along the shore nearby and cafés for fried fish. Saïd is usually the one sorting out taxis, trips and tips.",
        "facts_title": "The practical bit",
        "facts": [
            ("Beach", "A few steps — across the car park"),
            ("Parking", "Free public car park beside the house"),
            ("Bus", "Stop a few minutes’ walk away"),
            ("Airport", "A taxi ride — we can help arrange it"),
            ("Day trips", "Paradise Valley and more — ask us"),
            ("We speak", "Arabic, French, English"),
        ],
    },
    "ch4": {
        "id": "family",
        "n": "04",
        "label": "Second session",
        "title": "Back out. Then back to the family.",
        "lead": "Late in the day the boards go out again. Some evenings one of the brothers paddles out too — not a lesson, just a surf.",
        "fam_title": "A family house",
        "fam_text": "Line Up is our family’s house. Saïd and Zohair are brothers, the family makes breakfast, and between the shop, the house and the water there’s nearly always one of us around. Ask any of us anything.",
        "stat": "10",
        "stat_label": "Staff score on Booking.com",
        "stat_note": "We’re a small family, so that one is personal.",
        "quotes": [
            ("It felt like home as staff treat you as a member of family.", "Garig, Belgium", "Booking.com"),
            ("If you are looking for a place to learn or practice surfing that's the place I would recommend.", "Piekarec, Poland", "Booking.com"),
            ("Booked two nights but ended up extending my stay to a week", "Zoe, United Kingdom", "Booking.com"),
        ],
    },
    "ch5": {
        "id": "sunset",
        "n": "05",
        "label": "Sunset",
        "title": "Sunset from the roof.",
        "lead": "End the day the way it started: looking at the water. From the roof terrace you see the whole beach, and the sun goes down over the Atlantic, out past the line-up. Some evenings everyone ends up at the same table.",
        "roof_word": "The roof",
        "roof_lines": ["Breakfast up top", "The line-up all day", "Sunset at the end of it"],
        "img_alt": "Hazy late light over the sea and Anza beach, seen through a sea-view room window (toned photograph)",
        "caption": "Late light over Anza beach, from a sea-view room",
    },
    "ask": {
        "id": "ask",
        "title": "Ask for dates.",
        "lead": "Tell us when and who. This form writes the WhatsApp message for you — we reply with availability and today’s price.",
        "alt": "Rather book online? We’re on Booking.com.",
    },
}

FORM = {
    "checkin": "Check-in",
    "checkout": "Check-out",
    "adults": "Adults",
    "children": "Children (over 5)",
    "room": "Room",
    "room_opts": [
        ("", "Any room — you choose"),
        ("seaview", "Sea view · double or twin"),
        ("triple", "Sea view · triple"),
        ("private", "Private bathroom · double or twin"),
        ("compact", "Compact · double or twin"),
    ],
    "extras": "Also interested in",
    "extra_opts": [
        ("lessons", "Surf lessons"),
        ("rental", "Board & wetsuit rental"),
        ("taxi", "Help with an airport taxi"),
        ("meals", "Home-cooked lunch or dinner"),
    ],
    "name": "Your name",
    "note": "Anything else?",
    "note_ph": "Surf level, arrival time, dietary needs…",
    "optional": "optional",
    "submit": "Continue in WhatsApp",
    "errors": {
        "checkin": "Pick your check-in date.",
        "checkin_past": "Check-in can’t be in the past.",
        "checkout": "Pick your check-out date.",
        "order": "Check-out needs to be after check-in.",
        "summary": "Please check the highlighted fields.",
    },
    "msg": {
        "hello": "Hello Line Up! I'd like to ask about a stay.",
        "checkin": "Check-in",
        "checkout": "Check-out",
        "nights_one": "night",
        "nights_many": "nights",
        "guests": "Guests",
        "adult_one": "adult",
        "adult_many": "adults",
        "child_one": "child (over 5)",
        "child_many": "children (over 5)",
        "room": "Room",
        "extras": "Also interested in",
        "note": "Note",
        "name": "Name",
        "sent_from": "Sent from line-up-surf-house.peashoot.io",
    },
    "done_title": "Your message is ready in WhatsApp.",
    "done_text": "Send it, and we’ll reply with availability and today’s price.",
    "done_retry": "Didn’t open? Tap here",
    "done_call": "Or call us",
    "done_booking": "Or check dates on Booking.com",
    "done_edit": "Change something",
}

FOOTER = {
    "mural": "accommodation · Surf School · Shop",
    "address_label": "Find us",
    "contact_label": "Talk to us",
    "stay_label": "Staying",
    "stay_lines": ["Check-in 14:00 – midnight", "Check-out by 12:00", "Children over 5 welcome", "No pets · no parties"],
    "langs": "We speak Arabic, French and English.",
    "maps": "Open in Google Maps",
    "explore_label": "Around the site",
}

NOT_FOUND = {
    "title": "Wiped out.",
    "text": "That page isn’t here. The beach still is.",
    "back": "Back to Line Up",
}
