"""Texte français de Line Up Surf House — mêmes clés que en.py, écrit en français (pas une traduction mot à mot).

Chaque fait renvoie à SOURCE_OF_TRUTH.md ; les faits PROBABLE sont adoucis (« souvent », « certains soirs »,
« demandez-nous »). Les avis sont cités dans leur langue d'origine (lang="en" pour les avis anglais).
"""

LANG = "fr"
LOCALE = "fr_FR"

UI = {
    "skip": "Aller au contenu",
    "menu": "Menu",
    "close": "Fermer",
    "nav_label": "Navigation principale",
    "brand_sub": "Surf House · Anza",
    "cta_ask": "Demander vos dates",
    "cta_booking": "Booking.com",
    "cta_booking_long": "Nous voir sur Booking.com",
    "cta_whatsapp": "WhatsApp",
    "cta_whatsapp_long": "WhatsApp",
    "cta_call": "Appeler",
    "lang_switch": "English",
    "lang_switch_short": "EN",
    "ext": "s’ouvre dans un nouvel onglet",
    "wa_hello": "Bonjour Line Up ! J'aimerais avoir des infos pour un séjour.",
    "og_alt": "La fresque LINE UP sur notre maison à Anza : accommodation, Surf School, Shop",
}

NAV = [
    ("rooms", "Chambres"),
    ("surf", "École de surf"),
    ("house", "La maison"),
    ("anza", "Anza"),
]

PAGES_META = {
    "home": {
        "title": "Line Up Surf House · Anza, Agadir — surf house face au spot",
        "description": "Huit chambres privées à quelques pas de la plage d’Anza, un petit-déjeuner fait maison par notre famille, et notre école de surf et notre shop au rez-de-chaussée. Demandez vos dates sur WhatsApp.",
        "og_title": "Line Up Surf House — dormir face au spot, à Anza",
    },
    "rooms": {
        "title": "Chambres · Line Up Surf House, Anza — huit chambres privées face à la plage",
        "description": "Huit chambres privées à quelques pas de la plage d’Anza : doubles, twins et triples vue mer, et chambres avec salle d’eau privée. Petit-déjeuner inclus, pas de dortoir.",
        "crumb": "Chambres",
    },
    "surf": {
        "title": "École de surf & shop · Line Up Surf House, Anza",
        "description": "Notre école de surf et notre shop au rez-de-chaussée, à quelques pas de la plage d’Anza : des cours dès votre première vague, des softs, des planches dures et des combinaisons à louer.",
        "crumb": "École de surf",
    },
    "house": {
        "title": "La maison · Line Up Surf House, Anza — petit-déjeuner, famille, le toit",
        "description": "Une surf house familiale sur la plage d’Anza : le petit-déjeuner fait maison chaque matin, un tajine si vous commandez à l’avance, de l’aide pour les taxis et les excursions, et un toit-terrasse face à la mer.",
        "crumb": "La maison",
    },
    "anza": {
        "title": "Anza, Agadir · Line Up Surf House — la plage en bas de chez nous",
        "description": "Anza, c’est une petite ville de surf calme et locale, aux portes d’Agadir. La plage est de l’autre côté du parking, il y a des empreintes de dinosaures sur la côte, et on vous aide pour les taxis et les excursions.",
        "crumb": "Anza",
    },
    "book": {
        "title": "Demander vos dates · Line Up Surf House, Anza",
        "description": "Choisissez vos dates, votre chambre et vos extras : le formulaire prépare un message WhatsApp pour notre famille. On vous répond avec les disponibilités et le prix du jour. Ou appelez-nous, ou réservez sur Booking.com.",
        "crumb": "Demander vos dates",
    },
    "404": {
        "title": "Page introuvable · Line Up Surf House",
        "description": "Cette page a dérivé. Retour au Line Up Surf House, à Anza, Agadir.",
    },
}

HOME = {
    "cover": {
        "kicker": "Surf house · plage d’Anza, Agadir",
        "h1": "Dormir face <span>au spot.</span>",
        "lead": "Huit chambres privées à quelques pas de la plage d’Anza. Un petit-déjeuner fait maison par notre famille. Notre école de surf et notre shop au rez-de-chaussée.",
        "rating_score": "9,6",
        "rating_on": "sur Booking.com ·",
        "rating_link": "Y réserver",
        "horizon": "le line-up",
        "img_alt": "La plage d’Anza vue de l’étage du Line Up : le parking de la plage, le sable, l’écume et l’horizon de l’Atlantique sous un ciel bleu",
        "caption": "La plage d’Anza depuis l’étage du Line Up",
    },
    "ch1": {
        "id": "morning",
        "n": "01",
        "label": "Premières lueurs",
        "title": "Regarder les vagues avant le petit-déj.",
        "lead": "Quatre de nos huit chambres donnent droit sur la plage et les vagues. On ouvre le volet, on regarde ce que fait la mer, puis on monte manger.",
        "img_alt": "Encadrement de fenêtre sombre dans une chambre vue mer du Line Up, sur le parking de la plage, le sable et la mer",
        "caption": "Depuis une chambre vue mer",
        "bf_title": "Le petit-déjeuner, fait maison",
        "bf_text": "Le petit-déjeuner est inclus dans toutes les chambres, et c’est notre famille qui le prépare chaque matin. Il est végétarien et halal, et il change d’un jour à l’autre.",
        "bf_maybe": "Aujourd’hui, peut-être",
        "bf_items": ["jus d’orange frais", "œufs", "crêpes marocaines", "pain", "miel", "olives", "thé à la menthe ou café"],
        "bf_note": "Sans gluten ? Un avion très tôt ? Dites-le-nous, on fera de notre mieux.",
        "more": ("house", "Le petit-déj, la famille et le toit", "#breakfast"),
        "quote": "Le petit déjeuner est le meilleur que nous avons eu dans tout notre road trip au Maroc.",
        "quote_by": "Carole, France",
        "quote_src": "Booking.com",
    },
    "ch2": {
        "id": "surf",
        "n": "02",
        "label": "Première session",
        "title": "En bas : l’école de surf.",
        "lead": "Le rez-de-chaussée de la maison, c’est notre école de surf et notre shop. Les planches sur les racks, les combis sur le portant, et la plage juste de l’autre côté du parking.",
        "items": [
            ("Cours", "Grands débutants et surfeurs qui progressent, adultes et enfants. En privé ou en petit groupe — dites-nous votre niveau, on vous conseillera."),
            ("Location", "Softs, planches dures et combinaisons, juste devant la porte."),
            ("Prix", "Demandez le prix du jour sur WhatsApp."),
        ],
        "who": "Zohair est souvent celui qui est dans l’eau avec vous.",
        "quote": "Très facile d'avoir des cours de surf.",
        "quote_by": "Marielle, Belgique",
        "quote_src": "Booking.com",
        "set_label": "L’école de surf et le shop Line Up",
        "more": ("surf", "Cours, location et le shop"),
        "set": [
            ("shopfront", "La façade du Line Up : maison blanche aux fenêtres bleues, les portes du shop ouvertes sous la fresque LINE UP, une planche bleue sur des tréteaux", "La porte de notre shop. La banderole dit : « We are not the only ones but we are the best. »"),
            ("boards", "Des softs jaunes appuyées contre la fresque LINE UP peinte devant le shop", "Les softs, prêtes devant la fresque"),
            ("wetsuits", "Dans le shop Line Up : des combinaisons sur un portant, des t-shirts Line Up jaunes et un rack de planches jaunes", "Combis, planches, t-shirts Line Up"),
        ],
    },
    "ch3": {
        "id": "midday",
        "n": "03",
        "label": "Midi",
        "title": "Midi : manger, se poser, flâner.",
        "rooms_id": "rooms",
        "rooms_title": "Huit chambres. Pas de dortoir.",
        "rooms_lead": "Toutes les chambres sont privées, neuves et très propres, avec serviettes, douche et Wi-Fi gratuit. Les portes portent des noms venus de l’eau — cherchez « Reef room » et « Open face ».",
        "rooms": [
            {"img": "room-seaview", "count": "×2", "kind": "Vue mer", "name": "Double ou twin",
             "facts": ["Lit king ou deux lits simples", "Jusqu’à 2 personnes", "Fenêtre sur la plage", "Salle de bain partagée, hors de la chambre"],
             "alt": "Chambre vue mer en twin au Line Up : deux lits simples aux couvre-lits marron et une serviette LINE UP pliée"},
            {"img": "room-triple", "count": "×2", "kind": "Vue mer", "name": "Triple",
             "facts": ["Trois lits simples, ou un simple et un king", "Jusqu’à 3 personnes", "Grande fenêtre côté mer", "Salle de bain partagée, hors de la chambre"],
             "alt": "Triple vue mer au Line Up : un lit à côté d’une grande fenêtre ouverte, la plage et la mer dehors"},
            {"img": "room-private", "count": "×2", "kind": "Salle d’eau privée", "name": "Double ou twin",
             "facts": ["Lit king ou deux lits simples", "Jusqu’à 2 personnes", "Votre propre salle d’eau"],
             "alt": "Chambre double avec salle d’eau privée au Line Up : un grand lit avec des serviettes LINE UP dans une chambre blanche et propre"},
            {"img": "room-compact", "count": "×2", "kind": "Compacte", "name": "Double ou twin",
             "facts": ["Lit king ou deux lits simples", "Jusqu’à 2 personnes", "Demandez-nous la configuration de la salle de bain"],
             "plaques": ["Open face", "Reef room"],
             "alt": "La porte en pin de la chambre « Open face » au Line Up, sa plaque en bois au-dessus, et un lit double à l’intérieur"},
        ],
        "rooms_note": "Arrivée de 14 h à minuit · départ avant 12 h · enfants de plus de 5 ans bienvenus · pas de lit bébé ni de lit d’appoint · ni animaux, ni fêtes",
        "more": ("rooms", "Les quatre types de chambre, en détail"),
        "more_anza": ("anza", "En savoir plus sur Anza"),
        "lunch_title": "Déjeuner à la maison, sur demande",
        "lunch_text": "Commandez à l’avance et la famille vous cuisine un repas marocain, pour le déjeuner ou le dîner — un tajine au poulet ou à la kefta, peut-être de la loubia. C’est de la cuisine de maison, pas un restaurant, et c’est payé à part.",
        "anza_id": "anza",
        "anza_title": "Anza, autour de la maison",
        "anza_text": "Anza est une petite ville de surf calme et locale, aux portes d’Agadir — moins léchée que Taghazout, et c’est ce qu’on aime. Il y a des empreintes de dinosaures dans les rochers de la côte, tout près, et des cafés pour manger du poisson frit. Saïd est généralement celui qui s’occupe des taxis, des excursions et des bons plans.",
        "facts_title": "Côté pratique",
        "facts": [
            ("Plage", "À quelques pas — de l’autre côté du parking"),
            ("Parking", "Parking public gratuit à côté de la maison"),
            ("Bus", "Un arrêt à quelques minutes à pied"),
            ("Aéroport", "En taxi — on peut vous aider à l’organiser"),
            ("Excursions", "Paradise Valley et d’autres — demandez-nous"),
            ("On parle", "Arabe, français, anglais"),
        ],
    },
    "ch4": {
        "id": "family",
        "n": "04",
        "label": "Deuxième session",
        "title": "On y retourne. Puis retour en famille.",
        "lead": "En fin de journée, les planches ressortent. Certains soirs, l’un des frères va à l’eau aussi — pas un cours, juste une session.",
        "fam_title": "Une maison de famille",
        "fam_text": "Line Up, c’est la maison de notre famille. Saïd et Zohair sont frères, la famille prépare le petit-déjeuner, et entre le shop, la maison et l’eau, il y a presque toujours l’un de nous dans le coin. Demandez-nous ce que vous voulez.",
        "more": ("house", "La famille et la maison", "#family"),
        "stat": "10",
        "stat_label": "Note du personnel sur Booking.com",
        "stat_note": "On est une petite famille, alors celle-là nous touche personnellement.",
        "quotes": [
            ("Cette famille est accueillante et chaleureuse! On se sent comme à la maison.", "Barbara, France", "Booking.com"),
            ("Un accueil chaleureux et une ambiance de famille rendent le séjour ou l'expérience beaucoup plus agréable.", "Hamadi, Maroc", "Booking.com"),
            ("Adresse à garder pour un prochain séjour.", "Julien, France", "Booking.com"),
        ],
    },
    "ch5": {
        "id": "sunset",
        "n": "05",
        "label": "Coucher de soleil",
        "title": "Le coucher de soleil, depuis le toit.",
        "lead": "On finit la journée comme on l’a commencée : en regardant l’eau. Depuis le toit-terrasse, on voit toute la plage, et le soleil se couche sur l’Atlantique, au-delà du line-up. Certains soirs, tout le monde se retrouve à la même table.",
        "roof_word": "Le toit",
        "roof_lines": ["Petit-déj là-haut", "Le line-up toute la journée", "Le coucher de soleil pour finir"],
        "img_alt": "Lumière voilée de fin de journée sur la mer et la plage d’Anza, vue par la fenêtre d’une chambre vue mer (photo virée en bichromie)",
        "caption": "Fin de journée sur la plage d’Anza, depuis une chambre vue mer",
        "more": ("house", "Le toit, et le dîner sur demande", "#roof"),
    },
    "ask": {
        "id": "ask",
        "title": "Demandez vos dates.",
        "lead": "Dites-nous quand et qui. Ce formulaire écrit le message WhatsApp pour vous — on vous répond avec les disponibilités et le prix du jour.",
        "alt": "Vous préférez réserver en ligne ? Nous sommes sur Booking.com.",
    },
}

FORM = {
    "checkin": "Arrivée",
    "checkout": "Départ",
    "adults": "Adultes",
    "children": "Enfants (plus de 5 ans)",
    "room": "Chambre",
    "room_opts": [
        ("", "Peu importe — à vous de voir"),
        ("seaview", "Vue mer · double ou twin"),
        ("triple", "Vue mer · triple"),
        ("private", "Salle d’eau privée · double ou twin"),
        ("compact", "Compacte · double ou twin"),
    ],
    "extras": "Intéressé·e aussi par",
    "extra_opts": [
        ("lessons", "Cours de surf"),
        ("rental", "Location planche & combinaison"),
        ("taxi", "Aide pour un taxi vers l’aéroport"),
        ("meals", "Repas fait maison (sur demande)"),
    ],
    "name": "Votre nom",
    "note": "Autre chose ?",
    "note_ph": "Niveau de surf, heure d’arrivée, régime alimentaire…",
    "optional": "facultatif",
    "submit": "Continuer sur WhatsApp",
    "errors": {
        "checkin": "Choisissez votre date d’arrivée.",
        "checkin_past": "L’arrivée ne peut pas être dans le passé.",
        "checkout": "Choisissez votre date de départ.",
        "order": "Le départ doit être après l’arrivée.",
        "summary": "Vérifiez les champs signalés.",
    },
    "msg": {
        "hello": "Bonjour Line Up ! J'aimerais avoir des infos pour un séjour.",
        "sep": " : ",
        "checkin": "Arrivée",
        "checkout": "Départ",
        "nights_one": "nuit",
        "nights_many": "nuits",
        "guests": "Voyageurs",
        "adult_one": "adulte",
        "adult_many": "adultes",
        "child_one": "enfant (plus de 5 ans)",
        "child_many": "enfants (plus de 5 ans)",
        "room": "Chambre",
        "extras": "Intéressé·e aussi par",
        "note": "Note",
        "name": "Nom",
        "sent_from": "Envoyé depuis line-up-surf-house.peashoot.io",
    },
    "done_title": "Votre message est prêt dans WhatsApp.",
    "done_text": "Envoyez-le, et on vous répond avec les disponibilités et le prix du jour.",
    "done_retry": "Rien ne s’est ouvert ? Touchez ici",
    "done_call": "Ou appelez-nous",
    "done_booking": "Ou regardez les dates sur Booking.com",
    "done_edit": "Modifier",
}

FOOTER = {
    "mural": "accommodation · Surf School · Shop",
    "address_label": "Nous trouver",
    "contact_label": "Nous parler",
    "stay_label": "Séjour",
    "stay_lines": ["Arrivée 14 h – minuit", "Départ avant 12 h", "Enfants de plus de 5 ans bienvenus", "Ni animaux, ni fêtes"],
    "langs": "On parle arabe, français et anglais.",
    "maps": "Ouvrir dans Google Maps",
    "explore_label": "Sur le site",
}

NOT_FOUND = {
    "title": "Gamelle.",
    "text": "Cette page n’existe pas. La plage, si.",
    "back": "Retour au Line Up",
}

# ------------------------------------------------------------------ pages intérieures (phase 3)
DAY = ["Premières lueurs", "Première session", "Midi", "Deuxième session", "Coucher de soleil"]

ASK_BAND = {
    "text": "Donnez-nous vos dates et dites-nous qui vient. Le formulaire écrit le message WhatsApp pour vous, et on vous répond avec les disponibilités et le prix du jour.",
    "wa": "Ou écrivez-nous directement sur WhatsApp",
    "booking": "Ou réservez sur Booking.com",
}

NEXT = {
    "label": "La journée continue",
    "surf": ("Première session", "L’école de surf"),
    "rooms": ("Midi", "Les chambres"),
    "anza": ("Après-midi", "Anza"),
    "book": ("Coucher de soleil", "Demander vos dates"),
    "home": ("Demain", "Une journée au Line Up"),
}

ROOMS = {
    "mast": {
        "t": .5, "tone": "noon", "hour": "Midi", "kicker": "Les chambres",
        "h1": "Huit chambres privées.",
        "lead": "Quatre d’entre elles donnent droit sur la plage et les vagues. Les huit sont privées, neuves et très propres — pas de dortoir, pas de lits superposés. Trouvez celle qui va avec votre voyage.",
        "img": "view-window",
        "img_alt": "Encadrement de fenêtre noir dans une chambre vue mer du Line Up, autour du parking de la plage, du sable et de la mer sous un ciel bleu",
        "caption": "Depuis une chambre vue mer",
    },
    "ask_room": "Demander cette chambre",
    "types": [
        {"id": "sea-view", "room": "seaview", "kind": "Vue mer", "name": "Double ou twin", "count": "×2",
         "blurb": "On se réveille, on ouvre le volet, on regarde l’eau. Ces deux chambres donnent sur le parking et le sable, droit sur les vagues.",
         "specs": [("Lits", "Un lit king ou deux lits simples"), ("Personnes", "Jusqu’à 2"),
                   ("Salle de bain", "Partagée, juste en dehors de la chambre"), ("Fenêtre", "Sur la plage et la mer")],
         "imgs": [("room-seaview", "Chambre vue mer du Line Up en twin : deux lits simples aux couvre-lits marron et une serviette LINE UP pliée", "En twin"),
                  ("room-seaview-dbl", "Chambre vue mer du Line Up en double : un grand lit avec des coussins sous une fenêtre", "En double")]},
        {"id": "triple", "room": "triple", "kind": "Vue mer", "name": "Triple", "count": "×2",
         "blurb": "Pour trois copains en trip surf, ou une famille avec un enfant de plus de 5 ans. La même vue, un lit de plus.",
         "specs": [("Lits", "Trois lits simples, ou un simple et un king"), ("Personnes", "Jusqu’à 3"),
                   ("Salle de bain", "Partagée, juste en dehors de la chambre"), ("Fenêtre", "Sur la plage et la mer")],
         "imgs": [("room-triple", "Triple vue mer du Line Up : un lit à côté d’une grande fenêtre ouverte, la plage et la mer dehors", "Côté fenêtre"),
                  ("room-triple-3", "Triple vue mer du Line Up : trois lits simples aux couvre-lits marron et des serviettes LINE UP", "Trois lits simples")]},
        {"id": "private-bathroom", "room": "private", "kind": "Salle d’eau privée", "name": "Double ou twin", "count": "×2",
         "blurb": "Votre propre salle d’eau, dans la chambre. Murs blancs, lits en pin, serviettes LINE UP pliées sur le lit.",
         "specs": [("Lits", "Un lit king ou deux lits simples"), ("Personnes", "Jusqu’à 2"), ("Salle de bain", "Votre propre salle d’eau")],
         "imgs": [("room-private", "Chambre double avec salle d’eau privée au Line Up : un grand lit avec des serviettes LINE UP dans une chambre blanche et propre", "En double"),
                  ("room-private-twin", "Chambre twin avec salle d’eau privée au Line Up : deux lits simples en pin aux couvre-lits olive et un portemanteau", "En twin")]},
        {"id": "compact", "room": "compact", "kind": "Compacte", "name": "Double ou twin", "count": "×2",
         "blurb": "Nos deux chambres compactes, derrière les portes en pin marquées « Open face » et « Reef room ».",
         "specs": [("Lits", "Un lit king ou deux lits simples"), ("Personnes", "Jusqu’à 2"), ("Salle de bain", "Demandez-nous la configuration de la salle de bain")],
         "plaques": ["Open face", "Reef room"],
         "imgs": [("room-compact", "La porte en pin de la chambre « Open face » au Line Up, sa plaque en bois au-dessus, et un lit double à l’intérieur", "« Open face »"),
                  ("reef-plaque", "La porte en pin ouverte de la « Reef room » au Line Up sous sa plaque ovale, deux lits simples aux couvre-lits fleuris bleus à l’intérieur", "« Reef room »")]},
    ],
    "every": {
        "label": "Toutes les chambres",
        "title": "Ce qu’il y a dans chaque chambre. Et ce qu’on ne fait pas.",
        "has_title": "Dans chaque chambre",
        "has": ["Une chambre privée — pas de dortoir, pas de lits superposés", "Des serviettes", "Une douche, dans la chambre ou juste à côté",
                "Wi-Fi gratuit", "Non-fumeur", "Petit-déjeuner inclus"],
        "not_title": "Pas chez nous",
        "not": ["Lits bébé ou lits d’appoint", "Animaux", "Fêtes"],
        "doors_title": "Des noms sur les portes",
        "doors_text": "Certaines de nos portes portent des noms venus de l’eau. Cherchez ces deux-là.",
        "plaques": ["Open face", "Reef room"],
        "arrive_title": "Arriver et repartir",
        "arrive": [("Arrivée", "De 14 h à minuit"), ("Départ", "Avant 12 h"),
                   ("Avion tôt", "Dites-le-nous — on fera de notre mieux pour le petit-déj avant votre départ"),
                   ("Aéroport", "En taxi — on peut vous aider à l’organiser"),
                   ("En voiture", "Parking public gratuit à côté de la maison"),
                   ("Enfants", "De plus de 5 ans, bienvenus")],
    },
    "quote": ("La proximité de la plage, la propreté de l’établissement ainsi que la bienveillance et la disponibilité du personnel.", "Zineb, Maroc", "Booking.com"),
    "cta_title": "Vous avez trouvé votre chambre ?",
}

SURF = {
    "mast": {
        "t": .25, "tone": "sky", "hour": "Première session", "kicker": "L’école de surf",
        "h1": "L’école de surf est en bas.",
        "lead": "Line Up, c’est une maison avec sa propre école de surf et son shop au rez-de-chaussée. Les cours, les planches et les combis sont ici, dans la maison, et la plage juste de l’autre côté du parking.",
        "img": "shop-inside",
        "img_alt": "Dans le shop Line Up : des racks de planches en mousse jaunes, une chaise en plastique bleue et un parquet",
        "caption": "Dans notre shop",
    },
    "lessons": {
        "label": "Cours",
        "title": "Dès votre première vague.",
        "lead": "Grands débutants et surfeurs qui progressent, adultes et enfants. Dites-nous votre niveau, combien vous êtes et combien de temps vous restez, et on vous proposera ce qui vous convient.",
        "specs": [("Niveau", "Débutants et intermédiaires"), ("Format", "En privé ou en petit groupe"),
                  ("Enfants", "Bienvenus — dites-nous leur âge"), ("Prix", "Demandez le prix du jour sur WhatsApp")],
        "who": "Zohair est souvent celui qui est dans l’eau avec vous.",
        "quotes": [
            ("Très facile d'avoir des cours de surf.", "Marielle, Belgique", "Booking.com"),
            ("He was very professional, patient, he explained everything and he was with us all the time in the water.", "Youness, Maroc", "Booking.com", "en"),
        ],
    },
    "rental": {
        "label": "Location",
        "title": "Planches et combis, devant la porte.",
        "lead": "Des softs pour apprendre, des planches dures quand vous êtes prêt·e, des combinaisons sur le portant.",
        "text": "On prend le matériel au shop, on traverse le parking, on rame. Vous ne dormez pas chez nous ? Passez au shop et demandez.",
        "quotes": [("we rented surfing equipment from them and they also arranged a surf instructor for us.", "Rafal, Pologne", "Booking.com", "en")],
        "set_label": "Le shop Line Up",
        "set": [
            ("logo-board", "Le nez d’une planche Line Up jaune avec le logo rond « Line Up · Surf house », posée sur le sable sous un soleil bas", "Notre logo, sur une de nos planches"),
            ("boards", "Des softs jaunes appuyées contre la fresque LINE UP peinte devant le shop", "Les softs, prêtes devant la fresque"),
            ("wetsuits", "Dans le shop Line Up : des combinaisons sur un portant, des t-shirts Line Up jaunes et un rack de planches jaunes", "Combis, planches, t-shirts Line Up"),
        ],
    },
    "water": {
        "label": "L’eau",
        "title": "On regarde par la fenêtre.",
        "lead": "La plage d’Anza est juste devant la maison. Depuis les chambres vue mer et le toit, vous voyez les vagues avant de décider d’y aller.",
        "text": "Pas de prévisions ici. On a une fenêtre.",
        "img": "window",
        "img_alt": "Encadrement de fenêtre sombre dans une chambre vue mer du Line Up, sur le parking de la plage, le sable et la mer",
        "caption": "Depuis une chambre vue mer",
        "quotes": [("you can see the two main surf breaks in town from the window and roof of the property", "Marta, Pays-Bas", "Booking.com", "en")],
    },
    "cta_title": "Envie d’un cours ?",
}

HOUSE = {
    "mast": {
        "t": 0, "tone": "dawn", "hour": "Premières lueurs", "kicker": "La maison",
        "h1": "Une maison de famille sur la plage d’Anza.",
        "lead": "Line Up, c’est la maison de notre famille : le petit-déjeuner de notre cuisine chaque matin, deux frères entre le shop, la maison et l’eau, et un toit face à la plage pour finir la journée.",
        "img": "mural",
        "img_alt": "La fresque LINE UP sur notre mur — accommodation, Surf School, Shop — peinte sur une mer bleue avec des palmiers",
        "caption": "Notre mur, nos mots",
    },
    "breakfast": {
        "label": "Premières lueurs",
        "title": "Le petit-déjeuner, fait maison.",
        "lead": "Le petit-déjeuner est inclus dans toutes les chambres. Notre famille le prépare chaque matin, il est végétarien et halal, et il change d’un jour à l’autre. En ce moment, il est servi à l’étage, face à la mer.",
        "maybe": "Aujourd’hui, peut-être",
        "items": ["jus d’orange frais", "une omelette", "crêpes marocaines", "pain", "viennoiseries", "fromage", "olives", "miel", "thé à la menthe ou café"],
        "note": "Sans gluten, ou un autre régime ? Départ avant l’aube pour un avion ? Dites-le-nous en demandant vos dates, on fera de notre mieux.",
        "quotes": [
            ("Chambre confortable et très bon petit-déjeuner fait maison!", "Lucile, France", "Booking.com"),
            ("L’accueil chaleureux. Très bon petit déjeuner typique. Je recommande.", "Pierre-jean, France", "Booking.com"),
        ],
    },
    "family": {
        "label": "Toute la journée",
        "title": "Deux frères. Une famille. Une maison.",
        "lead": "Line Up est tenue en famille : nos parents en cuisine, et deux frères — Saïd et Zohair — entre le shop, la maison et l’eau. Il y a presque toujours l’un de nous dans le coin.",
        "said": "Saïd est généralement celui qui s’occupe des taxis, des excursions et des bons plans.",
        "zohair": "Zohair est souvent celui qui est dans l’eau avec vous.",
        "ask_title": "Demandez-nous",
        "ask_items": ["Un taxi pour Agadir", "Un taxi pour l’aéroport", "Des excursions — Paradise Valley et d’autres",
                      "Louer une voiture", "Une carte SIM locale", "Où manger du poisson frit"],
        "ask_note": "On parle arabe, français et anglais.",
    },
    "cooking": {
        "label": "Le soir",
        "title": "Un tajine, si vous prévenez.",
        "lead": "Ici, pas de restaurant ni de carte. Mais commandez à l’avance et la famille vous cuisine un repas marocain à la maison — un tajine au poulet ou à la kefta, peut-être de la loubia.",
        "text": "C’est payé à part ; demandez le prix du jour. Certains soirs, tout le monde se retrouve à la même table.",
        "quotes": [("On a super bien mangé, les plats sont faits maison et vraiment bons.", "Younes, Maroc", "Booking.com")],
    },
    "roof": {
        "label": "Coucher de soleil",
        "title": "Le toit, en fin de journée.",
        "lead": "Montez au-dessus des chambres jusqu’au toit-terrasse. De là-haut, on voit toute la plage et les vagues, et le soir, le soleil se couche sur l’Atlantique.",
        "word": "Le toit",
        "lines": ["Petit-déj là-haut", "Le line-up toute la journée", "Le coucher de soleil pour finir"],
        "quotes": [("gave many options to chill, see the sunset and be surrounded by the beach waves.", "Erika, Autriche", "Booking.com", "en")],
    },
    "scores": {
        "title": "Ce que nos hôtes nous donnent.",
        "items": [("9,6", "sur Booking.com"), ("10", "pour le personnel, sur Booking.com"),
                  ("9,8", "pour le rapport qualité-prix, sur Booking.com"), ("4,9", "sur Google")],
        "note": "On est une petite famille : la note du personnel nous touche personnellement.",
        "quotes": [
            ("Les membres du personnel étaient très aidants et agréables.", "Dany, Canada", "Booking.com"),
            ("je me suis senti chez moi, mon fils aussi.", "Omar, France", "Booking.com"),
            ("Mais surtout surtout la famille qui nous a accueillis qui est si adorable.", "Laure, France", "Booking.com"),
        ],
    },
    "rules": {
        "title": "Le règlement, en bref.",
        "text": "Une maison de famille au bord de la plage, pas une auberge pour faire la fête.",
        "items": [("Arrivée", "De 14 h à minuit"), ("Départ", "Avant 12 h"),
                  ("Enfants", "De plus de 5 ans, bienvenus ; pas de lit bébé ni de lit d’appoint"), ("Animaux", "Non acceptés"),
                  ("Fêtes", "Non autorisées"), ("On parle", "Arabe, français, anglais")],
    },
    "cta_title": "Venez dormir chez nous.",
}

ANZA = {
    "mast": {
        "t": .62, "tone": "sand", "hour": "Après-midi", "kicker": "Anza",
        "h1": "Anza, en bas de chez nous.",
        "lead": "Une petite ville de surf calme et locale, aux portes d’Agadir — moins léchée que Taghazout, et c’est ce qu’on aime.",
        "img": "anza-view", "wide": True,
        "img_alt": "Anza depuis l’étage du Line Up : le parking de la plage, le sable, des lignes d’écume et l’horizon de l’Atlantique sous un ciel bleu",
        "caption": "La plage d’Anza depuis l’étage du Line Up",
    },
    "front": {
        "label": "En sortant de la maison",
        "title": "Maison. Parking. Sable. Vagues.",
        "xs_label": "De la maison au line-up",
        "xs": [("house", "Line Up", "La maison, le shop en bas"),
               ("park", "Le parking", "Parking public gratuit"),
               ("sand", "Plage d’Anza", "Le sable"),
               ("surf", "L’écume", "Là où les vagues cassent"),
               ("line", "Le line-up", "Là où l’on attend la prochaine série")],
        "lead": "Entre nous et la plage, il n’y a que le parking à ciel ouvert. Vous traversez avec votre planche et vous êtes sur le sable. Si vous venez en voiture, le parking public à côté de la maison est gratuit.",
        "quotes": [("Emplacement idéal au bord de la mer. Très facile de se garer.", "Julien, France", "Booking.com")],
    },
    "wander": {
        "label": "Après-midi",
        "title": "Une petite ville de surf.",
        "lead": "Anza, ce n’est pas une station balnéaire. C’est une petite ville au bord de la mer, avec des cafés simples, du poisson frit, et une longue plage devant.",
        "text": "Vraie, pas léchée. Demandez-nous où manger.",
        "fp_title": "Des empreintes de dinosaures",
        "fp_text": "Longez la côte rocheuse, tout près, et vous trouverez des empreintes de dinosaures dans la roche — les plus anciens visiteurs d’Anza. Demandez-nous le chemin.",
        "quotes": [("Un endroit calme, petite ville calme.", "Marielle, Belgique", "Booking.com")],
    },
    "around": {
        "label": "Se déplacer",
        "title": "Bus, taxis et excursions.",
        "specs": [("Bus", "Un arrêt à quelques minutes à pied"), ("Taxi", "On vous aide à en trouver un"),
                  ("Aéroport", "En taxi — on peut vous aider à l’organiser"), ("En voiture", "Parking public gratuit à côté de la maison")],
        "who": "Saïd est généralement celui qui s’occupe des taxis, des excursions et des bons plans.",
        "trips_title": "Des excursions ? Demandez-nous.",
        "trips_text": "Paradise Valley et d’autres : dites-nous ce que vous aimeriez voir, on vous aide à l’organiser — ou à trouver une voiture de location.",
        "find_title": "Nous trouver",
    },
    "cta_title": "Venez voir Anza.",
}

BOOK = {
    "mast": {
        "t": 1, "tone": "dusk", "hour": "Coucher de soleil", "kicker": "Préparer la suite",
        "h1": "Demandez vos dates.",
        "lead": "Dites-nous quand vous venez et qui vient. Le formulaire écrit un message WhatsApp pour notre famille — vous n’avez plus qu’à l’envoyer. On vous répond avec les disponibilités et le prix du jour.",
    },
    "quote": ("pour moi ça ne sera pas la dernière fois.", "Omar, France", "Booking.com"),
    "form_label": "Formulaire de demande de dates",
    "how_title": "Comment ça marche",
    "steps": ["Indiquez vos dates et qui vient.", "Touchez « Continuer sur WhatsApp » : votre message s’ouvre, prêt à partir.",
              "Envoyez-le. On vous répond avec les disponibilités et le prix du jour."],
    "other_title": "Vous préférez parler ?",
    "know_title": "Bon à savoir",
    "know": [("Arrivée", "De 14 h à minuit"), ("Départ", "Avant 12 h"), ("Petit-déj", "Inclus"),
             ("Enfants", "De plus de 5 ans, bienvenus ; pas de lit bébé ni de lit d’appoint"), ("Animaux, fêtes", "Non")],
    "find_title": "Nous trouver",
}
